/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.fiemg.view;

import br.com.fiemg.conexao.conexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Fernanda
 */
public class CadUuario extends javax.swing.JInternalFrame {

    Connection con= null;
    PreparedStatement pst = null;
    ResultSet rs= null;
   
    public CadUuario() {
        initComponents();
        // iniciar a conexao  com classe a conexao
        con= conexao.conectar();
        desabilitarCampos();
    }
    // metodo de pesquisa no banco
    private void consultar(){
    
        String sql = " Select * from usuario "
                +" where id = ? ";
        try {
            // envia a consulta para banco
            pst = con.prepareStatement(sql);
            // seta o valor de td para primeiro do comando
            pst.setString(1, txtusaid.getText());
            // recebe  a consulta com executeQuery que sera usado
            // somente para a select
            rs = pst.executeQuery();
            if (rs.next())
            {
             txtusanome.setText(rs.getString(2));
             txtusalogin.setText(rs.getString(3));
             txtusasenha.setText(rs.getString(4));
             cbusaperfil.setSelectedItem(rs.getString(5));
            } else 
            {
            JOptionPane.showMessageDialog(null,"Usuario nao encontrado!");
            desabilitarCampos();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            
        }
    }
    private void Inserir(){
    String sql = " Insert into usuario( nome,login,senha,perfil )"
            + " values  (?,?,?,?)";
        try {
            pst= con.prepareStatement(sql);
            pst.setString(1, txtusanome.getText());
            pst.setString(2, txtusalogin.getText());
            pst.setString(3, txtusasenha.getText());
            pst.setString(4,cbusaperfil.getSelectedItem().toString());
            
            int op= pst.executeUpdate();
            if (op>0)
               JOptionPane.showMessageDialog(null, " Inserido com Sucesso ");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
        private void update(){
        
        String sql = "Update usuario SET nome = ?,login = ?,senha = ?,perfil = ? WHERE id = ?";
        try {
            pst= con.prepareStatement(sql);
            pst.setString(1, txtusanome.getText());
            pst.setString(2, txtusalogin.getText());
            pst.setString(3, txtusasenha.getText());
            pst.setString(4,cbusaperfil.getSelectedItem().toString());
            pst.setString(5, txtusaid.getText());
            int op= pst.executeUpdate();
            if (op>0)
               JOptionPane.showMessageDialog(null, " Editar com Sucesso ");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
        private void remover(){
            String sql = "Delete from usuario where id =?";
            int confirma = JOptionPane.showConfirmDialog(null, "Deseja relamente deletar?", "Atenção", JOptionPane.YES_NO_OPTION);
            if(confirma == JOptionPane.YES_OPTION);
        try {
            pst= con.prepareStatement(sql);
            pst.setString(1, txtusaid.getText());
            int op= pst.executeUpdate();
            if (op>0)
               JOptionPane.showConfirmDialog(null, " Deletado com Sucesso ");
            desabilitarCampos();
            
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }
        
        }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbusaperfil = new javax.swing.JComboBox<>();
        txtusanome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtusalogin = new javax.swing.JTextField();
        txtusaid = new javax.swing.JTextField();
        txtusasenha = new javax.swing.JTextField();
        btusaapagar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btusaeditar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btusapesquisar = new javax.swing.JButton();
        btusanovo = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro do Usuaáio");
        setPreferredSize(new java.awt.Dimension(400, 300));

        jLabel5.setText("Senha:");

        jLabel6.setText("Perfil:");

        cbusaperfil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "administrador", "usuario" }));

        jLabel1.setText("ID:");

        btusaapagar.setText("Apagar");
        btusaapagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btusaapagarActionPerformed(evt);
            }
        });

        jLabel3.setText("Nome:");

        btusaeditar.setText("Editar");
        btusaeditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btusaeditarActionPerformed(evt);
            }
        });

        jLabel4.setText("Login:");

        btusapesquisar.setText("Pesquisar");
        btusapesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btusapesquisarActionPerformed(evt);
            }
        });

        btusanovo.setText("Novo");
        btusanovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btusanovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtusaid, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtusasenha))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtusalogin, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cbusaperfil, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtusanome, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(btusanovo)
                .addGap(18, 18, 18)
                .addComponent(btusapesquisar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btusaeditar)
                .addGap(18, 18, 18)
                .addComponent(btusaapagar)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtusaid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtusanome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtusalogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtusasenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbusaperfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btusaeditar)
                    .addComponent(btusaapagar)
                    .addComponent(btusapesquisar)
                    .addComponent(btusanovo))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btusapesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btusapesquisarActionPerformed
        consultar();
    }//GEN-LAST:event_btusapesquisarActionPerformed

    private void btusanovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btusanovoActionPerformed
       Inserir();
    }//GEN-LAST:event_btusanovoActionPerformed

    private void btusaeditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btusaeditarActionPerformed
        update();
    }//GEN-LAST:event_btusaeditarActionPerformed

    private void btusaapagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btusaapagarActionPerformed
        remover();
    }//GEN-LAST:event_btusaapagarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btusaapagar;
    private javax.swing.JButton btusaeditar;
    private javax.swing.JButton btusanovo;
    private javax.swing.JButton btusapesquisar;
    private javax.swing.JComboBox<String> cbusaperfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtusaid;
    private javax.swing.JTextField txtusalogin;
    private javax.swing.JTextField txtusanome;
    private javax.swing.JTextField txtusasenha;
    // End of variables declaration//GEN-END:variables

    private void desabilitarCampos() {
            txtusanome.setText(null);
             txtusalogin.setText(null);
             txtusasenha.setText(null);
             cbusaperfil.setSelectedItem(null);
    }
}
